name: "Hello Actions"
description: "Greet Itachi"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet tut tut"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
